export const GPT_VERSION_CHANGE = 'GPT_VERSION_CHANGE';
export const CLEAR_GLOBAL_MESSAGES = 'CLEAR_GLOBAL_MESSAGES';
export const MESSAGES_COLLECTION_SAVE_SUCCESS = 'MESSAGES_COLLECTION_SAVE_SUCCESS'; 
