export const USER_INFO_SAVE_REQUEST = 'USER_INFO_SAVE_REQUEST';
export const USER_INFO_SAVE_SUCCESS = 'USER_INFO_SAVE_SUCCESS';
export const USER_INFO_SAVE_FAIL = 'USER_INFO_SAVE_FAIL';

export const SUBTRACT_CREDITS_REQUEST = 'SUBTRACT_CREDITS_REQUEST';
export const SUBTRACT_CREDITS_SUCCESS = 'SUBTRACT_CREDITS_SUCCESS';
export const SUBTRACT_CREDITS_FAIL    = 'SUBTRACT_CREDITS_FAIL'   ;

export const EDIT_USERNAME_EMAIL_REQUEST = 'EDIT_USERNAME_EMAIL_REQUEST';
export const EDIT_USERNAME_EMAIL_SUCCESS = 'EDIT_USERNAME_EMAIL_SUCCESS';
export const EDIT_USERNAME_EMAIL_FAIL = 'EDIT_USERNAME_EMAIL_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

